# Total number of flights cancelled in December 2013
SELECT YEAR, MONTH, COUNT(CANCELLED) AS TOTAL_CANCELLED
FROM airline
WHERE CANCELLED = 1
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH
LIMIT 10;
